/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201801251434.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_COM_MICROCHIP_CUSTOM_TYPES_SOMEIP_DEPLOYMENT_HPP_
#define V1_COM_MICROCHIP_CUSTOM_TYPES_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace microchip {
namespace CustomTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> attribStructDeployment_t;


// typecollection-specific deployments

} // namespace CustomTypes_
} // namespace microchip
} // namespace com
} // namespace v1

#endif // V1_COM_MICROCHIP_CUSTOM_TYPES_SOMEIP_DEPLOYMENT_HPP_
