/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201808092327.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * Interface to be implemented by server
 */
#ifndef V1_COM_MICROCHIP_I_Demo_STUB_DEFAULT_HPP_
#define V1_COM_MICROCHIP_I_Demo_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/com/microchip/IDemoStub.hpp>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace microchip {

/**
 * Provides a default implementation for IDemoStubRemoteEvent and
 * IDemoStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT IDemoStubDefault
    : public virtual IDemoStub {
public:
    COMMONAPI_EXPORT IDemoStubDefault();

    COMMONAPI_EXPORT IDemoStubRemoteEvent* initStubAdapter(const std::shared_ptr< IDemoStubAdapter> &_adapter);

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);

    COMMONAPI_EXPORT virtual const bool& getAttribBoolAttribute();
    COMMONAPI_EXPORT virtual const bool& getAttribBoolAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setAttribBoolAttribute(bool _value);
    COMMONAPI_EXPORT virtual void setAttribBoolAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value);

    /*
     * description: 
     * Retrieve Attrib
     */
    COMMONAPI_EXPORT virtual void GetAttrib(const std::shared_ptr<CommonAPI::ClientId> _client, GetAttribReply_t _reply);
    /*
     * description: 
     * Set Attrib
     */
    COMMONAPI_EXPORT virtual void SetAttrib(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value, SetAttribReply_t _reply);

    /*
     * description: 
     * Broadcast for notifing client
     */
    COMMONAPI_EXPORT virtual void fireStatusEvent(const std::string &_Message);

    
protected:
    COMMONAPI_EXPORT virtual bool trySetAttribBoolAttribute(bool _value);
    COMMONAPI_EXPORT virtual bool validateAttribBoolAttributeRequestedValue(const bool &_value);
    COMMONAPI_EXPORT virtual void onRemoteAttribBoolAttributeChanged();
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual IDemoStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(IDemoStubDefault *_defaultStub);

        COMMONAPI_EXPORT virtual bool onRemoteSetAttribBoolAttribute(bool _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetAttribBoolAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value);
        COMMONAPI_EXPORT virtual void onRemoteAttribBoolAttributeChanged();


    private:
        IDemoStubDefault *defaultStub_;
    };
protected:
    IDemoStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    bool attribBoolAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace microchip
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MICROCHIP_I_Demo_STUB_DEFAULT
